// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace OllamaLocalHostIntergration
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string OllamaLocalHostIntergrationString = "d1873e5c-8c8c-468f-a7b9-80a76f15e915";
        public static Guid OllamaLocalHostIntergration = new Guid(OllamaLocalHostIntergrationString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
        public const int OllamaContextMenu = 0x1000;
        public const int OllamaContextMenuGroup = 0x1100;
        public const int ExplainCodeCommand = 0x0200;
        public const int RefactorCodeCommand = 0x0300;
        public const int FindIssuesCommand = 0x0400;
    }
}